name: Trunk Build & Deploy

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build: #id
    name: Build 
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        portal: ['tp', 'rp', 'rh']
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2 #commands 
    
    - name: Install Node.js
      uses: actions/setup-node@v2 #commands 
      with:
        node-version: 12.13.0
    
    - name: Get Yarn cache directory
      id: yarn-cache-dir-path
      run: echo "::set-output name=dir::$(yarn cache dir)"

    - name: Use Yarn cache
      uses: actions/cache@v2
      id: yarn-cache
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-12.13.0-${{ hashFiles('**/yarn.lock') }}
    
    - name: Install yarn
      run: yarn install --frozen-lockfile --registry 'https://registry.yarnpkg.com'
    
    - name: Build project
      run: yarn build
    
    - name: Run tests
      run: yarn test

    - if: matrix.portal == 'tp' 
      name: Upload production-ready build files
      uses: actions/upload-artifact@v2
      with:
        name: production-files
        path: ./buildtp
        
    - if: matrix.portal == 'rp' 
      name: Upload production-ready build files
      uses: actions/upload-artifact@v2
      with:
        name: production-files
        path: ./buildrp    

    - if: matrix.portal == 'rh' 
      name: Upload production-ready build files
      uses: actions/upload-artifact@v2
      with:
        name: production-files
        path: ./buildrh   

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop'
    environment: 'develop'
    needs: build
    
    steps:
    - if: matrix.portal == 'rh' 
      name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: production-files
        path: ./buildrh
    
    - if: matrix.portal == 'rp' 
      name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: production-files
        path: ./buildrp
    
    - if: matrix.portal == 'tp' 
      name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: production-files
        path: ./buildtp

